# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from hey_robot.capability.contract.v1 import capability_pb2 as hey__robot_dot_capability_dot_v1_dot_capability__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in hey_robot/capability/contract/v1/capability_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CapabilityServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHealth = channel.unary_unary(
                '/hey_robot.capability.v1.CapabilityService/GetHealth',
                request_serializer=hey__robot_dot_capability_dot_v1_dot_capability__pb2.GetHealthRequest.SerializeToString,
                response_deserializer=hey__robot_dot_capability_dot_v1_dot_capability__pb2.GetHealthResponse.FromString,
                _registered_method=True)
        self.ExecuteCapability = channel.unary_unary(
                '/hey_robot.capability.v1.CapabilityService/ExecuteCapability',
                request_serializer=hey__robot_dot_capability_dot_v1_dot_capability__pb2.ExecuteCapabilityRequest.SerializeToString,
                response_deserializer=hey__robot_dot_capability_dot_v1_dot_capability__pb2.ExecuteCapabilityResponse.FromString,
                _registered_method=True)
        self.CancelCapability = channel.unary_unary(
                '/hey_robot.capability.v1.CapabilityService/CancelCapability',
                request_serializer=hey__robot_dot_capability_dot_v1_dot_capability__pb2.CancelCapabilityRequest.SerializeToString,
                response_deserializer=hey__robot_dot_capability_dot_v1_dot_capability__pb2.CancelCapabilityResponse.FromString,
                _registered_method=True)


class CapabilityServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCapability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelCapability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CapabilityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealth,
                    request_deserializer=hey__robot_dot_capability_dot_v1_dot_capability__pb2.GetHealthRequest.FromString,
                    response_serializer=hey__robot_dot_capability_dot_v1_dot_capability__pb2.GetHealthResponse.SerializeToString,
            ),
            'ExecuteCapability': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCapability,
                    request_deserializer=hey__robot_dot_capability_dot_v1_dot_capability__pb2.ExecuteCapabilityRequest.FromString,
                    response_serializer=hey__robot_dot_capability_dot_v1_dot_capability__pb2.ExecuteCapabilityResponse.SerializeToString,
            ),
            'CancelCapability': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelCapability,
                    request_deserializer=hey__robot_dot_capability_dot_v1_dot_capability__pb2.CancelCapabilityRequest.FromString,
                    response_serializer=hey__robot_dot_capability_dot_v1_dot_capability__pb2.CancelCapabilityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hey_robot.capability.v1.CapabilityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hey_robot.capability.v1.CapabilityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CapabilityService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hey_robot.capability.v1.CapabilityService/GetHealth',
            hey__robot_dot_capability_dot_v1_dot_capability__pb2.GetHealthRequest.SerializeToString,
            hey__robot_dot_capability_dot_v1_dot_capability__pb2.GetHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCapability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hey_robot.capability.v1.CapabilityService/ExecuteCapability',
            hey__robot_dot_capability_dot_v1_dot_capability__pb2.ExecuteCapabilityRequest.SerializeToString,
            hey__robot_dot_capability_dot_v1_dot_capability__pb2.ExecuteCapabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelCapability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hey_robot.capability.v1.CapabilityService/CancelCapability',
            hey__robot_dot_capability_dot_v1_dot_capability__pb2.CancelCapabilityRequest.SerializeToString,
            hey__robot_dot_capability_dot_v1_dot_capability__pb2.CancelCapabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

