[pytest]
log_format = %(asctime)s %(levelname)s %(message)s
log_date_format = %Y-%m-%d %H:%M:%S
testpaths = tests
markers =
    integration: integration tests
python_files =
    test_*.py
    *_tests.py
    tests.py
addopts = 
    --maxfail=1 
    --capture=no 
    --tb=auto 
    --cov=hey_robot
    --cov-report=term-missing:skip-covered 
    --cov-report=xml:cov.xml 
    --junitxml=report.xml 
    --cov-fail-under=85
    -vv
asyncio_mode = auto
env =
    server__use_ray=false
    server__enable_proxy=true
    load_builtin_plugins=["echo","proxy"]
    sentry__enable=false
    test__silent=true
