from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PROTO_FILE = ROOT / "proto/hey_robot/capability/v1/capability.proto"
CONTRACT_DIR = ROOT / "src/hey_robot/capability/contract/v1"
LEGACY_GENERATED_DIR = ROOT / "src/hey_robot/capability/v1"


def test_capability_proto_source_and_generated_contract_layout() -> None:
    assert PROTO_FILE.exists()
    assert CONTRACT_DIR.exists()
    assert not LEGACY_GENERATED_DIR.exists()

    expected_files = {
        "capability_pb2.py",
        "capability_pb2.pyi",
        "capability_pb2_grpc.py",
        "__init__.py",
    }
    actual_files = {path.name for path in CONTRACT_DIR.iterdir() if path.is_file()}
    assert expected_files.issubset(actual_files)


def test_generated_contract_files_keep_expected_codegen_markers() -> None:
    pb2_text = (CONTRACT_DIR / "capability_pb2.py").read_text(encoding="utf-8")
    pyi_text = (CONTRACT_DIR / "capability_pb2.pyi").read_text(encoding="utf-8")
    grpc_text = (CONTRACT_DIR / "capability_pb2_grpc.py").read_text(encoding="utf-8")

    assert "Generated by the protocol buffer compiler.  DO NOT EDIT!" in pb2_text
    assert "Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!" in (
        grpc_text
    )
    assert "class GetHealthRequest" in pyi_text
    assert "from hey_robot.capability.contract.v1 import capability_pb2 as " in (
        grpc_text
    )
    assert "from hey_robot.capability.v1 import" not in grpc_text
