from __future__ import annotations

from typing import Any, Protocol


class RobotSkillAPI(Protocol):
    async def run(self, name: str, arguments: dict[str, Any] | None = None) -> Any: ...

    async def move_base(self, **arguments: Any) -> Any: ...

    async def turn_base(self, **arguments: Any) -> Any: ...

    async def stop_motion(self, **arguments: Any) -> Any: ...

    async def set_arm_pose(self, **arguments: Any) -> Any: ...

    async def move_arm_joints(self, **arguments: Any) -> Any: ...

    async def set_gripper(self, **arguments: Any) -> Any: ...

    async def reset_posture(self, **arguments: Any) -> Any: ...


class PerceptionAPI(Protocol):
    async def run(self, name: str, arguments: dict[str, Any] | None = None) -> Any: ...

    async def inspect_scene(self, **arguments: Any) -> Any: ...

    async def look_around(self, **arguments: Any) -> Any: ...

    async def detect_marker(self, **arguments: Any) -> Any: ...


class CapabilityAPI(Protocol):
    async def call(self, name: str, arguments: dict[str, Any]) -> Any: ...
