from __future__ import annotations

import base64
import binascii
import contextlib
import hashlib
import hmac
import io
import json
import mimetypes
import time
import uuid
from pathlib import Path, PurePosixPath
from typing import Any, cast

import numpy as np
from PIL import Image

from hey_robot.logging import HeyRobotLogger
from hey_robot.protocol import ArtifactRef, ImageRef, MediaRef

logger = HeyRobotLogger(name="store")

_ALLOWED_MEDIA_MIMES = {
    "image/jpeg",
    "image/png",
    "image/webp",
    "application/json",
    "application/x.numpy-npz",
    "application/octet-stream",
}


class MediaStoreError(ValueError):
    """Raised when media cannot be safely stored or resolved."""


class LocalMediaStore:
    """Content-addressable local media/artifact store.

    Services exchange `media://local/...` URIs, never raw image arrays or large
    policy observations. HTTP/UI access is provided by signed URLs generated by
    `MediaSigner`.
    """

    def __init__(
        self, root: str | Path = "runtime/media", *, max_items: int = 5000
    ) -> None:
        self.root = Path(root)
        self.root.mkdir(parents=True, exist_ok=True)
        self.max_items = max(1, int(max_items))

    def put_image(
        self,
        image: np.ndarray,
        *,
        robot_id: str,
        frame_id: int,
        camera: str | None = None,
        content_type: str = "image/jpeg",
        metadata: dict[str, Any] | None = None,
    ) -> ImageRef:
        if content_type not in {"image/jpeg", "image/png"}:
            raise MediaStoreError(f"unsupported image content type: {content_type}")
        image = _as_uint8_rgb(image)
        suffix = ".jpg" if content_type == "image/jpeg" else ".png"
        rel_dir = (
            Path("images") / _safe_segment(robot_id) / _safe_segment(camera or "cam")
        )
        target_dir = self._ensure_subdir(rel_dir)
        name = f"frame_{int(frame_id):08d}_{uuid.uuid4().hex[:12]}{suffix}"
        path = target_dir / name
        pil = Image.fromarray(image)
        self._write_parent(path)
        if content_type == "image/jpeg":
            pil.save(path, format="JPEG", quality=85)
        else:
            pil.save(path, format="PNG")
        stat = path.stat()
        digest = _sha256_file(path)
        self._enforce_limit("images")
        return ImageRef(
            uri=self.uri_for_path(path),
            camera=camera,
            width=int(image.shape[1]),
            height=int(image.shape[0]),
            timestamp=time.time(),
            content_type=content_type,
            size_bytes=int(stat.st_size),
            sha256=digest,
            metadata=dict(metadata or {}),
        )

    def put_json_artifact(
        self,
        payload: Any,
        *,
        artifact_type: str,
        role: str | None = None,
        robot_id: str | None = None,
        frame_id: int | None = None,
        name: str | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> ArtifactRef:
        rel_dir = (
            Path("artifacts")
            / _safe_segment(robot_id or "shared")
            / _safe_segment(artifact_type)
        )
        target_dir = self._ensure_subdir(rel_dir)
        stem = _safe_segment(name or role or artifact_type)
        if frame_id is not None:
            stem = f"frame_{int(frame_id):08d}_{stem}"
        path = target_dir / f"{stem}_{uuid.uuid4().hex[:12]}.json"
        raw = json.dumps(payload, ensure_ascii=False, separators=(",", ":")).encode(
            "utf-8"
        )
        self._write_bytes(path, raw)
        stat = path.stat()
        digest = _sha256_file(path)
        self._enforce_limit("artifacts")
        return ArtifactRef(
            uri=self.uri_for_path(path),
            artifact_type=artifact_type,
            role=role,
            name=name,
            content_type="application/json",
            size_bytes=int(stat.st_size),
            sha256=digest,
            metadata=dict(metadata or {}),
        )

    def put_npz_artifact(
        self,
        payload: Any,
        *,
        artifact_type: str,
        role: str | None = None,
        robot_id: str | None = None,
        frame_id: int | None = None,
        name: str | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> ArtifactRef:
        rel_dir = (
            Path("artifacts")
            / _safe_segment(robot_id or "shared")
            / _safe_segment(artifact_type)
        )
        target_dir = self._ensure_subdir(rel_dir)
        stem = _safe_segment(name or role or artifact_type)
        if frame_id is not None:
            stem = f"frame_{int(frame_id):08d}_{stem}"
        path = target_dir / f"{stem}_{uuid.uuid4().hex[:12]}.npz"
        raw = _encode_typed_npz(payload)
        self._write_bytes(path, raw)
        stat = path.stat()
        digest = _sha256_file(path)
        self._enforce_limit("artifacts")
        return ArtifactRef(
            uri=self.uri_for_path(path),
            artifact_type=artifact_type,
            role=role,
            name=name,
            content_type="application/x.numpy-npz",
            size_bytes=int(stat.st_size),
            sha256=digest,
            metadata={**dict(metadata or {}), "encoding": "typed-npz"},
        )

    def put_bytes(
        self,
        data: bytes,
        *,
        media_type: str,
        content_type: str,
        name: str | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> MediaRef:
        if content_type not in _ALLOWED_MEDIA_MIMES:
            raise MediaStoreError(f"unsupported media content type: {content_type}")
        suffix = mimetypes.guess_extension(content_type) or ".bin"
        rel_dir = Path("uploads") / _safe_segment(media_type)
        target_dir = self._ensure_subdir(rel_dir)
        filename = f"{uuid.uuid4().hex[:12]}_{_safe_segment(name or 'upload')}{suffix}"
        path = target_dir / filename
        self._write_bytes(path, data)
        stat = path.stat()
        digest = _sha256_file(path)
        self._enforce_limit("uploads")
        return MediaRef(
            uri=self.uri_for_path(path),
            media_type=media_type,
            name=name,
            content_type=content_type,
            size_bytes=int(stat.st_size),
            sha256=digest,
            metadata=dict(metadata or {}),
        )

    def resolve_image(self, ref: ImageRef) -> np.ndarray:
        path = self.path_for_uri(ref.uri)
        with Image.open(path) as image:
            return np.array(image.convert("RGB"))

    def load_json_artifact(self, ref: ArtifactRef) -> Any:
        path = self.path_for_uri(ref.uri)
        if ref.content_type not in {None, "application/json"}:
            raise MediaStoreError(f"artifact is not JSON: {ref.uri}")
        with path.open(encoding="utf-8") as handle:
            return json.load(handle)

    def load_npz_artifact(self, ref: ArtifactRef) -> Any:
        path = self.path_for_uri(ref.uri)
        if ref.content_type != "application/x.numpy-npz":
            raise MediaStoreError(f"artifact is not typed NPZ: {ref.uri}")
        return _decode_typed_npz(path.read_bytes())

    def load_artifact(self, ref: ArtifactRef) -> Any:
        if ref.content_type == "application/x.numpy-npz":
            return self.load_npz_artifact(ref)
        if ref.content_type in {None, "application/json"}:
            return self.load_json_artifact(ref)
        raise MediaStoreError(f"unsupported artifact content type: {ref.content_type}")

    def path_for_uri(self, uri: str) -> Path:
        prefix = "media://local/"
        if not uri.startswith(prefix):
            raise MediaStoreError(f"unsupported media uri: {uri}")
        rel_raw = uri.removeprefix(prefix)
        rel = PurePosixPath(rel_raw)
        if rel.is_absolute() or any(part in {"", ".", ".."} for part in rel.parts):
            raise MediaStoreError("unsafe media uri")
        path = (self.root / Path(*rel.parts)).resolve()
        root = self.root.resolve()
        try:
            path.relative_to(root)
        except ValueError as exc:
            raise MediaStoreError("media uri escapes media root") from exc
        if not path.is_file():
            raise MediaStoreError(f"media object not found: {uri}")
        return path

    def uri_for_path(self, path: Path) -> str:
        resolved = path.resolve()
        root = self.root.resolve()
        try:
            rel = resolved.relative_to(root)
        except ValueError as exc:
            raise MediaStoreError("path escapes media root") from exc
        return f"media://local/{rel.as_posix()}"

    def recent(
        self, *, kind: str | None = None, limit: int = 100
    ) -> list[dict[str, Any]]:
        roots = (
            [self.root / kind]
            if kind
            else [self.root / "images", self.root / "artifacts", self.root / "uploads"]
        )
        files: list[Path] = []
        for root in roots:
            if root.exists():
                files.extend(path for path in root.rglob("*") if path.is_file())
        files = [path for path in files if _path_mtime(path) is not None]
        files.sort(key=lambda path: _path_mtime(path) or 0.0, reverse=True)
        out: list[dict[str, Any]] = []
        for path in files[: max(1, min(limit, self.max_items))]:
            with contextlib.suppress(OSError):
                stat = path.stat()
                out.append(
                    {
                        "uri": self.uri_for_path(path),
                        "name": path.name,
                        "size_bytes": int(stat.st_size),
                        "updated_at": stat.st_mtime,
                        "content_type": mimetypes.guess_type(path.name)[0]
                        or "application/octet-stream",
                    }
                )
        return out

    def _ensure_subdir(self, rel: Path) -> Path:
        target = (self.root / rel).resolve()
        root = self.root.resolve()
        try:
            target.relative_to(root)
        except ValueError as exc:
            raise MediaStoreError("media directory escapes media root") from exc
        target.mkdir(parents=True, exist_ok=True)
        return target

    def _write_parent(self, path: Path) -> None:
        root = self.root.resolve()
        parent = path.parent.resolve()
        try:
            parent.relative_to(root)
        except ValueError as exc:
            raise MediaStoreError("media path escapes media root") from exc
        parent.mkdir(parents=True, exist_ok=True)

    def _write_bytes(self, path: Path, data: bytes) -> None:
        self._write_parent(path)
        try:
            path.write_bytes(data)
        except FileNotFoundError:
            self._write_parent(path)
            path.write_bytes(data)

    def _enforce_limit(self, kind: str) -> None:
        root = self.root / kind
        if not root.exists():
            return
        files = [
            (mtime, path)
            for path in root.rglob("*")
            if path.is_file() and (mtime := _path_mtime(path)) is not None
        ]
        files.sort(key=lambda item: item[0])
        overflow = len(files) - self.max_items
        for _, path in files[: max(0, overflow)]:
            with contextlib.suppress(OSError):
                path.unlink()


class MediaResolver:
    def __init__(self, store: LocalMediaStore) -> None:
        self.store = store

    def resolve_images(self, refs: list[ImageRef]) -> list[np.ndarray]:
        images: list[np.ndarray] = []
        for ref in refs:
            try:
                images.append(self.store.resolve_image(ref))
            except Exception as exc:
                logger.debug(f"image ref 解析失败 {ref.uri}: {exc}")
                continue
        return images

    def load_artifact(
        self, refs: list[ArtifactRef], *, role: str, artifact_type: str | None = None
    ) -> Any | None:
        for ref in refs:
            if ref.role != role:
                continue
            if artifact_type is not None and ref.artifact_type != artifact_type:
                continue
            return self.store.load_artifact(ref)
        return None


class MediaSigner:
    """HMAC signed URL helper for local MediaStore objects."""

    def __init__(
        self,
        store: LocalMediaStore,
        *,
        secret: bytes | str | None = None,
        route_prefix: str = "/media",
    ) -> None:
        self.store = store
        if secret is None:
            secret = uuid.uuid4().bytes + uuid.uuid4().bytes
        self.secret = secret.encode("utf-8") if isinstance(secret, str) else secret
        self.route_prefix = route_prefix.rstrip("/")

    def sign(self, uri: str) -> str | None:
        try:
            self.store.path_for_uri(uri)
        except Exception:
            return None
        payload = _b64url_encode(uri.encode("utf-8"))
        mac = hmac.new(self.secret, payload.encode("ascii"), hashlib.sha256).digest()[
            :16
        ]
        return f"{self.route_prefix}/{_b64url_encode(mac)}/{payload}"

    def verify(self, signature: str, payload: str) -> str:
        try:
            provided_mac = _b64url_decode(signature)
        except (ValueError, binascii.Error) as exc:
            raise MediaStoreError("invalid media signature") from exc
        expected_mac = hmac.new(
            self.secret, payload.encode("ascii"), hashlib.sha256
        ).digest()[:16]
        if not hmac.compare_digest(expected_mac, provided_mac):
            raise MediaStoreError("invalid media signature")
        try:
            uri = _b64url_decode(payload).decode("utf-8")
        except (ValueError, binascii.Error, UnicodeDecodeError) as exc:
            raise MediaStoreError("invalid media payload") from exc
        self.store.path_for_uri(uri)
        return uri


def _safe_segment(value: str) -> str:
    clean = "".join(
        ch if ch.isalnum() or ch in {"-", "_", "."} else "_" for ch in str(value)
    ).strip("._")
    return clean or "item"


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _b64url_encode(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode("ascii")


def _b64url_decode(value: str) -> bytes:
    return base64.urlsafe_b64decode(value + ("=" * (-len(value) % 4)))


def _as_uint8_rgb(image: np.ndarray) -> np.ndarray:
    arr = np.asarray(image)
    if arr.ndim == 4 and arr.shape[0] == 1:
        arr = arr[0]
    if arr.ndim == 2:
        arr = np.stack([arr, arr, arr], axis=-1)
    if arr.ndim != 3:
        raise MediaStoreError(
            f"expected image with 2 or 3 dimensions, got shape {arr.shape}"
        )
    if arr.shape[-1] == 4:
        arr = arr[..., :3]
    if arr.shape[-1] != 3:
        raise MediaStoreError(f"expected RGB-like image, got shape {arr.shape}")
    if arr.dtype != np.uint8:
        if arr.max(initial=0) <= 1.0:
            arr = arr * 255
        arr = np.clip(arr, 0, 255).astype(np.uint8)
    return arr


def _path_mtime(path: Path) -> float | None:
    with contextlib.suppress(OSError):
        return path.stat().st_mtime
    return None


def _encode_typed_npz(payload: Any) -> bytes:
    arrays: dict[str, np.ndarray] = {}
    counter = 0

    def encode(value: Any) -> Any:
        nonlocal counter
        if isinstance(value, dict):
            return {
                "kind": "dict",
                "items": {str(key): encode(item) for key, item in value.items()},
            }
        if isinstance(value, tuple):
            return {"kind": "tuple", "items": [encode(item) for item in value]}
        if isinstance(value, list):
            return {"kind": "list", "items": [encode(item) for item in value]}
        if isinstance(value, np.ndarray):
            key = f"arr_{counter}"
            counter += 1
            arrays[key] = value
            return {"kind": "ndarray", "key": key}
        if isinstance(value, np.generic):
            return {
                "kind": "scalar",
                "dtype": str(value.dtype),
                "value": value.item(),
            }
        if value is None or isinstance(value, str | int | float | bool):
            return {"kind": "json", "value": value}
        raise MediaStoreError(
            f"typed NPZ artifact cannot encode {type(value).__name__}"
        )

    manifest = json.dumps(
        encode(payload), ensure_ascii=False, separators=(",", ":")
    ).encode("utf-8")
    arrays["__manifest__"] = np.frombuffer(manifest, dtype=np.uint8)
    out = io.BytesIO()
    np.savez_compressed(out, **cast(Any, arrays))
    return out.getvalue()


def _decode_typed_npz(raw: bytes) -> Any:
    with np.load(io.BytesIO(raw), allow_pickle=False) as data:
        manifest = json.loads(bytes(data["__manifest__"].tolist()).decode("utf-8"))

        def decode(node: Any) -> Any:
            kind = node["kind"]
            if kind == "dict":
                return {key: decode(value) for key, value in node["items"].items()}
            if kind == "tuple":
                return tuple(decode(value) for value in node["items"])
            if kind == "list":
                return [decode(value) for value in node["items"]]
            if kind == "ndarray":
                return np.asarray(data[node["key"]])
            if kind == "scalar":
                return np.asarray(node["value"], dtype=np.dtype(node["dtype"])).item()
            if kind == "json":
                return node["value"]
            raise MediaStoreError(f"typed NPZ artifact cannot decode kind {kind!r}")

        return decode(manifest)
